services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile

        ports:
            - "8080:8000"
        
        env_file:
            - .env

        depends_on:
            - db

    db:
        image: postgres:latest

        ports:
            - "5532:5532"

        env_file:
            - .env

        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
            - PGPORT=5532